Add documentation for running SP with Istio
datawire/ambassador pull request #2987
Opened 2020-09-24 20:52 UTC by nbkrause

Service preview can intercept request to services in an Istio mesh. 

There are some configuration changes that need to be made to support this. 

1. The `istio-proxy` **must not** run alongside service preview components

2. The `traffic-agent` **must** set `AMBASSADOR_ENVOY_BASE_ID: "1"` so it can
run in the same pod as the `istio-proxy`.

2020-09-24 20:55 UTC, nbkrause commented
Shoot I need to rebase this 🤦

2020-09-24 22:04 UTC, richarddli requested changes

2020-09-24 22:04 UTC, richarddli commented on docs/topics/using/edgectl/service-preview-reference.md
> +Much like a service mesh, the Service Preview `traffic-agent` runs as a sidecar to the container running your application. Luckily, due to the magic of service mesh Pod networking, Service Preview wi
Delete "Much like a service mesh" because a service mesh isn't just the sidecar, it's also other stuff. So we can avoid the comparison.

2020-09-29 15:32 UTC, richarddli approved these changes

2020-09-29 16:46 UTC, merged